clear; clc; close all;


fontS=14;


load GRiskKPR3RCNfoc_2024_11_30_06_37-4k51shp.mat
sigmavect'
alpha
beta
delta
rho
theta
A

S_SDZ1=S_SDZ;
S_SDZ1(:,7,:)=0;
S_CSDCOMPDATA1=S_CSDCOMPDATA;
S_CSDCOMPDATA1(:,7,:)=0;
S_NSDCOMPDATA1=S_NSDCOMPDATA;
S_NSDCOMPDATA1(:,7,:)=0;
S_YSDCOMPDATA1=S_YSDCOMPDATA;
S_YSDCOMPDATA1(:,7,:)=0;
sigmavect1=sigmavect;
labels1={['20']; ['15']; ['10']; ['5']};
lsigmavect1=lsigmavect;
lsdzvect1=lsdzvect+1;



load GRiskKPRRCNfocPC_2024_03_23_00_04-4k51hp.mat
sigmavect'
alpha
beta
delta
rho
theta
A

S_SDZ2=S_SDZ(:,2:5,1:5);
S_CSDCOMPDATA2=S_CSDCOMPDATA(:,2:5,1:5);
S_NSDCOMPDATA2=S_NSDCOMPDATA(:,2:5,1:5);
S_YSDCOMPDATA2=S_YSDCOMPDATA(:,2:5,1:5);
sigmavect2=sigmavect(1:5);
labels2={['4']; ['3']; ['2']; ['1']; ['.5']};;
lsigmavect2=length(sigmavect2);
lsdzvect2=lsdzvect;


labels=[labels1; labels2];
colors1={
[0.3686    0.3098    0.6353];
[0.2005    0.5593    0.7380];
[0.4558    0.7897    0.6458];
[0.7616    0.9058    0.6299]}; % colors generated by linspecer.m
colors2={
[0.9277    0.9583    0.6442];
[0.9820    0.9206    0.6372];
[0.9942    0.7583    0.4312];
[0.9684    0.4799    0.2723];
[0.8525    0.2654    0.3082];
[0.6196    0.0039    0.2588]};


fontS=14;

figure('Renderer', 'painters', 'Position', [10 10 1000 400]);
tiledlayout(1,2,'TileSpacing','compact');
nexttile;
hold on;
for i=1:lsigmavect1
    plot(S_SDZ1(:,:,i), S_CSDCOMPDATA1(:,:,i), 'color',colors1{i,1},'linewidth',1.5);
end
for i=1:lsigmavect2
    plot(S_SDZ2(:,:,i), S_CSDCOMPDATA2(:,:,i), 'color',colors2{i,1},'linewidth',1.5);
end
plot(S_SDZ2(:,:,1), 1.3856*ones(4),'color',[.5 .5 .5],'LineStyle',':');
axis([-.0015 .072 -.05 3.4]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
lgd=legend(labels,'Position',[.12+.015 .45 .06 .45],'FontSize',fontS)
title(lgd,'RRAC','FontSize',fontS,'FontWeight','normal');
title('SD consumption','Interpreter','Latex','FontSize',fontS+4);
hold off;


nexttile;
hold on;
for i=1:lsigmavect1
    plot(S_SDZ1(:,:,i), S_NSDCOMPDATA1(:,:,i), 'color',colors1{i,1},'linewidth',1.5);
end
for i=1:lsigmavect2
    plot(S_SDZ2(:,:,i), S_NSDCOMPDATA2(:,:,i), 'color',colors2{i,1},'linewidth',1.5);
end
plot(S_SDZ2(:,:,i), 2.0873*ones(4),'color',[.5 .5 .5],'LineStyle',':');
axis([-.0015 .072 -.05 3.9]);
ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
lgd=legend(labels,'Position',[.82 .15 .06 .45],'FontSize',fontS);
title(lgd,'RRAC','FontSize',fontS,'FontWeight','normal');
title('SD hours','Interpreter','Latex','FontSize',fontS+4);
hold off;
exportgraphics(gcf,"GRiskRBCnKPRNfocFIGHP.eps","Resolution",300)


figure;
hold on;
for i=1:lsigmavect1
    plot(S_SDZ1(:,:,i), S_YSDCOMPDATA1(:,:,i), 'color',colors1{i,1},'linewidth',1.5);
end
for i=1:lsigmavect2
    plot(S_SDZ2(:,:,i), S_YSDCOMPDATA2(:,:,i), 'color',colors2{i,1},'linewidth',1.5);
end
plot(S_SDZ2(:,:,i), 1.6443*ones(4),'color',[.5 .5 .5],'LineStyle',':');
axis([-.001 .072 -.15 6.3]);
%ytickformat('%.1f')
xlabel('\sigma','FontSize',fontS+2);
fontsize(gca,fontS,"points")
centeraxes(gca);
lgd=legend(labels,'Position',[.2+.03 .5+.05 .04 .2],'FontSize',fontS);
title(lgd,'RRAC','FontSize',fontS,'FontWeight','normal');
title('SD GDP','Interpreter','Latex','FontSize',fontS+4);
hold off;
exportgraphics(gcf,"GRiskRBCnKPRNfocFIGHPy.eps","Resolution",300)





% load GRiskADSeNfoc_2024_11_22_01_21-2k51s.mat;
% sigmavect'
% alpha
% beta
% delta
% rho
% theta
% A
% 
% S_SDZ1=S_SDZ(:,3:7,:);
% S_KBAR1=S_KBAR(:,3:7,:);
% S_YBAR1=S_YBAR(:,3:7,:);
% S_CBAR1=S_CBAR(:,3:7,:);
% S_NBAR1=S_NBAR(:,3:7,:);
% sigmavect1=sigmavect;
% labels1={[char(949) '=20']; [char(949) '=15']; [char(949) '=10']; [char(949) '=5']};
% 
% 
% load GRiskADSeNfoc_2024_11_25_06_03-4k51.mat
% sigmavect'
% alpha
% beta
% delta
% rho
% theta
% A
% 
% S_SDZ2=S_SDZ;
% S_KBAR2=S_KBAR;
% S_YBAR2=S_YBAR;
% S_CBAR2=S_CBAR;
% S_NBAR2=S_NBAR;
% sigmavect2=sigmavect;
% labels2=labels;
% 
% 
% labels=[labels1; labels2];
% colors={
% [0.3686    0.3098    0.6353];
% [0.2005    0.5593    0.7380];
% [0.4558    0.7897    0.6458];
% [0.7616    0.9058    0.6299];
% [0.9277    0.9583    0.6442];
% [0.9820    0.9206    0.6372];
% [0.9942    0.7583    0.4312];
% [0.9684    0.4799    0.2723];
% [0.8525    0.2654    0.3082];
% [0.6196    0.0039    0.2588]}; % colors generated by linspecer.m
% 
% S_SDZ = cat(3,S_SDZ1,S_SDZ2);
% S_KBAR = cat(3,S_KBAR1,S_KBAR2);
% S_YBAR = cat(3,S_NBAR,S_NBAR2);
% S_CBAR = cat(3,S_CBAR1,S_CBAR2);
% S_NBAR = cat(3,S_NBAR1,S_NBAR2);
% sigmavect=[sigmavect1;sigmavect2];
% lsigmavect=length(sigmavect);
% lsdzvect=size(S_SDZ,2);
% 
% 
% figure('Renderer', 'painters', 'Position', [10 10 1000 800]);
% tiledlayout(2,2,'TileSpacing','compact');
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_KBAR(:,:,i)/S_KBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     % text(S_SDZ(:,1,i)*1.01, (S_KBAR(:,1,i)/S_KBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% for i=1:lsigmavect
%     text(S_SDZ(:,1,i)*1.01, (S_KBAR(:,1,i)/S_KBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .2 -.1 17.6]);
% % ytickformat('%.0f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Mean capital $\bar k$ and investment','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_YBAR(:,:,i)/S_YBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     % text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .2 -.05 5.9]);
% % ytickformat('%.1f')
% i=1;
% text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100+.2, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=2;
% text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100+.13, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=3;
% text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100-.1, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=4;
% text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100+.08, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=5;
% text(S_SDZ(:,1,i)*1.01, (S_YBAR(:,1,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=6;
% text(S_SDZ(:,3,i)*1.02, (S_YBAR(:,3,i)/S_YBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Mean production','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_CBAR(:,:,i)/S_CBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
%     % text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% for i=3:lsigmavect-1
%     text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .2 -.05 5.9]);
% i=1;
% text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100-.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=2;
% text(S_SDZ(:,1,i)*1.01, (S_CBAR(:,1,i)/S_CBAR(:,lsdzvect,i)-1)*100+.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=6;
% text(S_SDZ(:,3,i)*1.02, (S_CBAR(:,3,i)/S_CBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% % ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Mean consumption','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% 
% nexttile;
% hold on;
% for i=1:lsigmavect
%     plot(S_SDZ(:,:,i), (S_NBAR(:,:,i)/S_NBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',1.5);
% end
% for i=[1:2 4]
%     text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% end
% axis([-.001 .2 -.7 2.4]);
% i=3;
% text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100+.1, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=5;
% text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100-.05, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% i=6;
% text(S_SDZ(:,3,i)*1.02, (S_NBAR(:,3,i)/S_NBAR(:,lsdzvect,i)-1)*100, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% % i=4;
% % text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100+.03, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% % i=5;
% % text(S_SDZ(:,1,i)*1.01, (S_NBAR(:,1,i)/S_NBAR(:,lsdzvect,i)-1)*100-.008, labels{i,1},'color',colors{i,1},'FontSize',fontS);
% % plot(S_SDZ(:,:,i), (S_NBAR(:,:,i)/S_NBAR(:,lsdzvect,i)-1)*100, 'color',colors{i,1},'linewidth',3);
% % ytickformat('%.1f')
% xlabel('\sigma','FontSize',fontS+2);
% fontsize(gca,fontS,"points")
% centeraxes(gca);
% title('Mean labor','Interpreter','Latex','FontSize',fontS+4);
% hold off;
% exportgraphics(gcf,"GRiskRBCKPRNfocFIGstats.eps","Resolution",300)
% 
% 
% 
% 
% 
% 
